version: '3'

services:
  php:
    environment:
      - XDEBUG_SESSION=docker-server
    build:
      ./server
    volumes:
      - ./server/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
          - mysql
    links:
          - mysql
  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql-tmp:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_access
      MYSQL_DATABASE: city_complaint
